# Generated by Django 3.1 on 2020-08-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('creator', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('rights', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('game_image', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('D', 'DEVELOPMENT'), ('P', 'PUBLISH'), ('R', 'RESTRICTED'), ('PR', 'PRIVATE')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameEditor.game')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameEditor.game')),
            ],
        ),
    ]
