# Generated by Django 3.1 on 2020-08-23 08:00

import ciberscratch.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=8, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('G', 'GRADO'), ('M', 'MASTER'), ('P', 'FORMACIÓN PERMANENT'), ('MO', 'MOOC'), ('O', 'OTRO')], max_length=200)),
                ('URL', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=200)),
                ('access_key', models.CharField(max_length=64)),
                ('groups_enabled', models.BooleanField(default=True)),
                ('group_max_members', models.IntegerField(default=0, validators=[ciberscratch.validators.Validator.validate_positive_number])),
                ('group_min_members', models.IntegerField(default=0, validators=[ciberscratch.validators.Validator.validate_positive_number])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('creation_group_player_permission', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameMonitor.course')),
            ],
        ),
    ]
