# Generated by Django 3.1 on 2020-08-25 06:38

import ciberscratch.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameMonitor', '0002_classroom_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameMonitor.classroom'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameMonitor.course'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[ciberscratch.validators.Validator.is_student]),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[ciberscratch.validators.Validator.is_lecturer]),
        ),
    ]
