# Generated by Django 3.1 on 2020-08-25 13:28

import ciberscratch.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameMonitor', '0003_auto_20200825_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='classroom',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, validators=[ciberscratch.validators.Validator.is_lecturer]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='access_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 28, 0, 493917))),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameMonitor.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[ciberscratch.validators.Validator.is_student])),
            ],
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 28, 0, 493917))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameMonitor.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[ciberscratch.validators.Validator.is_lecturer])),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(through='GameMonitor.Lecturers', to=settings.AUTH_USER_MODEL),
        ),
    ]
