# Generated by Django 3.1 on 2020-08-25 13:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameMonitor', '0006_auto_20200825_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student_body',
            field=models.ManyToManyField(through='GameMonitor.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 30, 24, 522972)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 15, 30, 24, 522972)),
        ),
    ]
