# Generated by Django 3.0.3 on 2020-03-03 13:46

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('related', models.IntegerField(default=0, validators=[common.validators.Validator.validate_positive_number])),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
