# Generated by Django 3.0.3 on 2020-03-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_learnactivity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnactivity',
            name='group',
        ),
    ]
