# Generated by Django 3.0.3 on 2020-03-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_learnactivity_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('clue_text', models.CharField(max_length=1000)),
                ('hiddeninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HiddenInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GroupClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Clue')),
                ('group_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GroupArtifactInfo')),
            ],
        ),
    ]
